server:
  port: 4040
spring:
  application:
    name: micro-user
  profiles.active: dev
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      enabled: true
      health-check:
        initial-delay: 1s
seata:
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    # 参考tc服务自己的registry.conf中的配置
    type: nacos
    nacos: # tc
      server-addr: 192.168.60.138:8848
      group: SEATA_GROUP
      application: seata-server # tc服务在nacos中的服务名称
      cluster: default
  service:
    vgroup-mapping: # 事务组与TC服务cluster的映射关系
      order-service-seata-service-group: default
