spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        shared-dataids: application.yaml # 共享库
        refreshable-dataids: application.yaml # 共享库
      discovery.server-addr: 127.0.0.1:8848
