spring:
  application:
    name: a-start-test
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.60.138:80
        namespace: zzl
  redis:
    database: 0 # 数据库，每个库由16384（0~16383）槽位组成，实现了库的分片
    password: bdyh@2020 # 密码
    timeout: 50000 # 连接超时时间
    cluster:
      nodes:
        - 192.168.4.26:6379
        - 192.168.4.26:6380
        - 192.168.4.26:6479
        - 192.168.4.26:6480
        - 192.168.4.26:6579
        - 192.168.4.26:6580
      max-redirects: 3 # 获取失败 最大重定向次数
    lettuce:
      pool:
        max-idle: 10
        max-active: 10
        min-idle: 0
      cluster:
        refresh: # 动态感应
          adaptive: true
          period: 10000


    profiles:
    active: dev
