spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: lind-auth-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.60.138:80
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.4.26:3306/oauth2_config?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  server:
    port: 5000

  mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
