server:
  port: 9091
# Keycloak Configuration
keycloak:
  auth-server-url: http://192.168.4.26:8080/auth
  realm: demo
  resource: demo-app
  client-key-password: 8a0d0153-6b60-4676-8f3a-dedf58affeb1
  public-client: false #如果设置为true，则适配器不会将客户端的凭据发送到Keycloak。 这是可选的。 默认值为false。
  principal-attribute: preferred_username
  use-resource-role-mappings: false #如果设置为true，则适配器将在令牌内部查找用户的应用程序级角色映射。 如果为false，它将查看用户角色映射的领域级别。 这是可选的。 默认值为false。
  cors: true
uaa:
  permitAll: /users,/kafka,/kafka/create,/doc.html
  callbackUri: http://localhost:9090/token/authorizationCodeLogin

