server.port: 6061
spring:
   application.name: start-oauth
   profiles.active: dev
   redis:
      host: localhost
      database: 1
      port: 6379
      jedis:
         pool:
            max-idle: 6
            max-active: 32
            max-wait: 100
            min-idle: 4