server:
  port: 9090
# Keycloak Configuration
keycloak:
  auth-server-url: http://192.168.4.26:8080/auth
  realm: demo
  resource: democlient
  client-key-password: 58e23419-c53f-49bc-bad6-b696756bba26
  public-client: false #如果设置为true，则适配器不会将客户端的凭据发送到Keycloak。 这是可选的。 默认值为false。
  principal-attribute: preferred_username
  use-resource-role-mappings: false #如果设置为true，则适配器将在令牌内部查找用户的应用程序级角色映射。 如果为false，它将查看用户角色映射的领域级别。 这是可选的。 默认值为false。
  cors: true
uaa:
  permitAll: /users,/kafka,/kafka/create,/doc.html,/api/news,/redirect,/index
  callbackUri: http://localhost:9090/token/authorizationCodeRedirect #认证中心地址

