server:
  port: 9090
lind:
  logger:
    level: Info
    type: File
    enable: true
  ratelimit:
    enable: true
    limit: 1
    timeout: 5 #毫秒
spring:
  # Redis
  redis:
    host: 127.0.0.1
    #password: bdyh@2020
    # 数据库索引 默认0
    database: 10
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S
  elasticsearch:
    rest:
      uris: 192.168.0.204:9200
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.4.26:3306/zhfw?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456

# 指定kafka 代理地址，可以多个
  kafka:
    listener:
      missing-topics-fatal: false # 没有主题就自动建立
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# hbase配置
winter:
  hbase:
    zookeeper:
      quorum: 192.168.10.37,192.168.10.38,192.168.10.39
    name-space: nezha

zookeeper:
  znode:
    parent: /hbase
# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lind.test.entity,com.lind.testshade.entity
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # 数据库大写下划线转换
    #capital-mode: true
    # 逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
