server:
  port: 9091
lind:
  ratelimit:
    enable: false
    limit: 1
    timeout: 5 #毫秒
  redis:
    lock:
      enable: true
      autoRelease: false
      interrupt: true
      registryKey: lind-lock

spring:
  # Redis
  redis:
    host: 127.0.0.1
    # 数据库索引 默认0
    database: 10


  elasticsearch:
    rest:
      uris: localhost:9200

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false # 没有主题就自动建立
    consumer:
      group-id: lind1
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
