server:
  port: 9090
lind:
  logger:
    level: Info
    type: File
    enable: true
  ratelimit:
    enable: true
    limit: 100
    timeout: 1000
spring:
  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 10
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S