server:
  port: 9091
lind:
  ratelimit:
    enable: false
    limit: 1
    timeout: 5 #毫秒
  redis:
    lock:
      enable: true
      autoRelease: false
      interrupt: true
      registryKey: lind-lock

spring:
  # Redis
  redis:
    host: 127.0.0.1
    # 数据库索引 默认0
    database: 10


  elasticsearch:
    rest:
      uris: localhost:9200

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false # 没有主题就自动建立
    consumer:
      group-id: lind1
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  freemarker:
    suffix: .ftl                                 # 设置模板后缀名
    content-type: text/html                      # 设置文档类型
    charset: UTF-8                               # 设置页面编码格式
    cache: false                                 # 设置页面缓存
    template-loader-path: classpath:/templates   # 设置ftl文件路径
  mvc:
    static-path-pattern: /static         # 设置静态文件路径，js,css等

# hbase配置
hbase:
  zookeeper:
    quorum: 192.168.10.37,192.168.10.38,192.168.10.39
  name-space: nezha
zookeeper:
  znode:
    parent: /hbase
