spring:
  application:
    name: oauthdemo
server.port: 8082

# Keycloak Configuration
keycloak:
  credentials:
    secret: 7599ee5a-f04b-43d3-b299-7fa6208ae0af
  auth-server-url: http://192.168.119.130:8080/auth
  realm: demo
  resource: demoproduct
  public-client: false #如果设置为true，则适配器不会将客户端的凭据发送到Keycloak。 这是可选的。 默认值为false。
  principal-attribute: preferred_username
  use-resource-role-mappings: false #如果设置为true，则适配器将在令牌内部查找用户的应用程序级角色映射。 如果为false，它将查看用户角色映射的领域级别。 这是可选的。 默认值为false。
  cors: true
